#!/bin/bash

echo "starting php -S on localhost:8096, it will be shutdown after exiting the web page"
if [ "$(uname)" == 'Darwin' ] 
  then
	open http://localhost:8096/editor/;
  else
	x-www-browser http://localhost:8096/editor/ &
fi
php -S localhost:8096 > /dev/null 2>&1 &
echo "It's strongly recommanded to update your repository before editing doc"
read -p'Do a git pull for you [n]: ' pullok
if [ "$pullok" == 'y' ]
  then
	git pull;
fi
exit 1;
